In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df  = pd.read_csv('text_summarization_dataset.csv')

In [4]:
df

,id,document,summary
0,1,The quick brown fox jumps over the lazy dog.,Fox jumps over dog.
1,2,Artificial intelligence is transforming the te...,AI is changing tech.
2,3,The sun rises in the east and sets in the west.,"Sun rises east, sets west."
3,4,Machine learning is a subset of artificial int...,ML is part of AI.
4,5,John went to the store to buy some groceries.,John bought groceries.
...,...,...,...
1995,1996,The quick brown fox jumps over the lazy dog.,Fox jumps over dog.
1996,1997,Artificial intelligence is transforming the te...,AI is changing tech.
1997,1998,The sun rises in the east and sets in the west.,"Sun rises east, sets west."
1998,1999,Machine learning is a subset of artificial int...,ML is part of AI.
1999,2000,John went to the store to buy some groceries.,John bought groceries.

In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenize the documents and summaries
tokenizer = Tokenizer(num_words=50000)  # Limit vocab size
tokenizer.fit_on_texts(df['document'])
document_sequences = tokenizer.texts_to_sequences(df['document'])
summary_sequences = tokenizer.texts_to_sequences(df['summary'])

# Pad sequences
max_len_doc = 500  # Example max length for documents
max_len_summary = 50  # Example max length for summaries

document_padded = pad_sequences(document_sequences, maxlen=max_len_doc, padding='post')
summary_padded = pad_sequences(summary_sequences, maxlen=max_len_summary, padding='post')